# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Transactor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Transactor.proto',
  package='protocol',
  syntax='proto3',
  serialized_pb=_b('\n\x10Transactor.proto\x12\x08protocol\"\'\n\x12MultihashReference\x12\x11\n\treference\x18\x01 \x01(\t2g\n\x11TransactorService\x12R\n\x14\x46\x65tchObjectChainHead\x12\x1c.protocol.MultihashReference\x1a\x1c.protocol.MultihashReferenceB#\n!io.mediachain.protocol.transactorb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MULTIHASHREFERENCE = _descriptor.Descriptor(
  name='MultihashReference',
  full_name='protocol.MultihashReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reference', full_name='protocol.MultihashReference.reference', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['MultihashReference'] = _MULTIHASHREFERENCE

MultihashReference = _reflection.GeneratedProtocolMessageType('MultihashReference', (_message.Message,), dict(
  DESCRIPTOR = _MULTIHASHREFERENCE,
  __module__ = 'Transactor_pb2'
  # @@protoc_insertion_point(class_scope:protocol.MultihashReference)
  ))
_sym_db.RegisterMessage(MultihashReference)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n!io.mediachain.protocol.transactor'))
import abc
from grpc.beta import implementations as beta_implementations
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

class BetaTransactorServiceServicer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def FetchObjectChainHead(self, request, context):
    raise NotImplementedError()

class BetaTransactorServiceStub(object):
  """The interface to which stubs will conform."""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def FetchObjectChainHead(self, request, timeout):
    raise NotImplementedError()
  FetchObjectChainHead.future = None

def beta_create_TransactorService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  import Transactor_pb2
  import Transactor_pb2
  request_deserializers = {
    ('protocol.TransactorService', 'FetchObjectChainHead'): Transactor_pb2.MultihashReference.FromString,
  }
  response_serializers = {
    ('protocol.TransactorService', 'FetchObjectChainHead'): Transactor_pb2.MultihashReference.SerializeToString,
  }
  method_implementations = {
    ('protocol.TransactorService', 'FetchObjectChainHead'): face_utilities.unary_unary_inline(servicer.FetchObjectChainHead),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)

def beta_create_TransactorService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  import Transactor_pb2
  import Transactor_pb2
  request_serializers = {
    ('protocol.TransactorService', 'FetchObjectChainHead'): Transactor_pb2.MultihashReference.SerializeToString,
  }
  response_deserializers = {
    ('protocol.TransactorService', 'FetchObjectChainHead'): Transactor_pb2.MultihashReference.FromString,
  }
  cardinalities = {
    'FetchObjectChainHead': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'protocol.TransactorService', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
