# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Transactor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Transactor.proto',
  package='protocol',
  syntax='proto3',
  serialized_pb=_b('\n\x10Transactor.proto\x12\x08protocol\"\'\n\x12MultihashReference\x12\x11\n\treference\x18\x01 \x01(\t2g\n\x11TransactorService\x12R\n\x14\x46\x65tchObjectChainHead\x12\x1c.protocol.MultihashReference\x1a\x1c.protocol.MultihashReferenceB#\n!io.mediachain.protocol.transactorb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MULTIHASHREFERENCE = _descriptor.Descriptor(
  name='MultihashReference',
  full_name='protocol.MultihashReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reference', full_name='protocol.MultihashReference.reference', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['MultihashReference'] = _MULTIHASHREFERENCE

MultihashReference = _reflection.GeneratedProtocolMessageType('MultihashReference', (_message.Message,), dict(
  DESCRIPTOR = _MULTIHASHREFERENCE,
  __module__ = 'Transactor_pb2'
  # @@protoc_insertion_point(class_scope:protocol.MultihashReference)
  ))
_sym_db.RegisterMessage(MultihashReference)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n!io.mediachain.protocol.transactor'))
# @@protoc_insertion_point(module_scope)
